### ISSUE TITLE
Download to a folder: exits with an error

### ISSUE THREAD

**Issue by icemtel** [securityinfive/RSSDownloader#5]
Thanks for your script - it helped me to download what I wanted.

In case you want to improve it, I found an issue: If I download to a folder, the script exists with an error. 

Steps to reproduce:
```
mkdir manson
python RSsDownloader2.0.py https://feeds.soundcloud.com/users/soundcloud:users:311749379/sounds.rss 0 manson
```
Output:
```
Downloading - 1064577700-markmanson-the-virtue-of-delayed-gratification.mp3
Traceback (most recent call last):
  File "RSsDownloader2.0.py", line 156, in <module>
    main()
  File "RSsDownloader2.0.py", line 150, in main
    Download_Files(local_target_dir, RSS_Feed_Items, How_Many,args["Title"])
  File "RSsDownloader2.0.py", line 93, in Download_Files
    wget.download(mp3_link['href'], target_dir)
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\wget.py", line 533, in download
    filename = filename_fix_existing(filename)
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\wget.py", line 269, in filename_fix_existing
    name, ext = filename.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

- I tried to download in the current directory and it worked.
- I tried with a different feed (`http://zenhabitsaudio.com/feed/podcast/`) and it worked. 

I am using python 3.8, wget 3.2

P.S. also a smaller issue: I get the progress messages only AFTER the whole script was finished.

**Comment by securityinfive** [comment]
Thanks,

   A community member added those enhancements to make it 2.0. I can, or you, can reach out to him. Check the history for the contributor. 

 

From: icemtel ***@***.***> 
Sent: Saturday, April 9, 2022 1:42 PM
To: securityinfive/RSSDownloader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [securityinfive/RSSDownloader] Download to a folder: exits with an error (Issue #5)

 

Thanks for your script - it helped me to download what I wanted.

In case you want to improve it, I found an issue: If I download to a folder, the script exists with an error.

Steps to reproduce:

mkdir manson
python RSsDownloader2.0.py https://feeds.soundcloud.com/users/soundcloud:users:311749379/sounds.rss 0 manson

Output:

Downloading - 1064577700-markmanson-the-virtue-of-delayed-gratification.mp3
Traceback (most recent call last):
  File "RSsDownloader2.0.py", line 156, in <module>
    main()
  File "RSsDownloader2.0.py", line 150, in main
    Download_Files(local_target_dir, RSS_Feed_Items, How_Many,args["Title"])
  File "RSsDownloader2.0.py", line 93, in Download_Files
    wget.download(mp3_link['href'], target_dir)
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\wget.py", line 533, in download
    filename = filename_fix_existing(filename)
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\wget.py", line 269, in filename_fix_existing
    name, ext = filename.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

*	I tried to download in the current directory and it worked.
*	I tried with a different feed (http://zenhabitsaudio.com/feed/podcast/) and it worked.

I am using python 3.8, wget 3.2

P.S. also a smaller issue: I get the progress messages only AFTER the whole script was finished.

**Comment by icemtel** [comment]
In the history it says that you, @securityinfive , have uploaded the file ;)
